apiVersion: hops.ops.com.ai/v1alpha1
kind: CertStack
metadata:
  name: certs
  namespace: default
spec:
  clusterName: production-cluster
  namespace: cert-manager
  # renovate: datasource=helm depName=cert-manager registryUrl=https://charts.jetstack.io
  chartVersion: v1.19.2
  values:
    prometheus:
      enabled: true
    webhook:
      replicaCount: 2
